# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=7)),
                ('uri', models.TextField()),
                ('origin', models.GenericIPAddressField()),
                ('headers', models.TextField()),
                ('args', models.TextField()),
            ],
        ),
    ]
