# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpbucket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlogentry',
            options={'verbose_name_plural': 'Request log entries'},
        ),
    ]
